# Generated by Django 3.2.7 on 2021-11-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_customer_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], default='C', max_length=15),
        ),
    ]
