# Generated by Django 3.2.7 on 2021-09-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loan', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='auth.user')),
                ('ranking', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('B', 'Basic')], default='B', max_length=15)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=225)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.IntegerField(max_length=150)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking_app.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking_app.customer'),
        ),
    ]
