# Generated by Django 3.2.7 on 2021-10-02 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
