# Generated by Django 3.2.7 on 2021-10-09 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0004_ledger_cd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='cd',
        ),
        migrations.AddField(
            model_name='ledger',
            name='Account_owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
