# Generated by Django 3.2.8 on 2021-10-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0005_auto_20211009_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='Account_owner',
            new_name='account_owner',
        ),
    ]
